-- 0059: let link_transcripts hold a short-form transcript at all.
--
-- THE BUG THIS FIXES IS SILENT, WHICH IS WHY IT SURVIVED. Two check constraints
-- written when YouTube was the only thing that could produce a transcript:
--
--   link_transcripts_source_check    CHECK (source = 'youtube')
--   link_transcripts_provider_check  CHECK (provider IN ('ytdlp','browser','disk_backfill','manual'))
--
-- Every short-form transcript violates the first. apply-suggestion wraps its
-- transcript persist in try/catch and logs a warning, so a blocked insert
-- produced a perfectly normal-looking result: link created, relation created,
-- suggestion auto_approved, and no transcript — indistinguishable from a clip
-- that had no speech. Verified end-to-end on 2026-09-09: three TikToks collected
-- for muay-thai/switch-kick, two carrying a whisper transcript in
-- evidence_json.transcript_full, and link_transcripts stayed empty for all three.
-- scripts/fetch-shortform-transcripts.mjs writes the same two values and was
-- blocked the same way, so the 141-clip backfill could never have landed either.
--
-- WHY 'whisper' IS A NEW PROVIDER RATHER THAN REUSING ONE. provider records how
-- the text was obtained, and that is the one thing genuinely different about
-- short-form: 'ytdlp' and 'browser' both mean "the platform's own caption track,
-- authored or auto-generated by the platform", while 'whisper' means "we
-- transcribed the audio ourselves". They have different failure modes and
-- different accuracy, and a later question about transcript quality cannot be
-- answered if they are recorded as the same thing. apply-suggestion previously
-- collapsed anything that was not 'browser' to 'ytdlp', so short-form would have
-- been mislabelled even had the source constraint allowed it through.
begin;

alter table public.link_transcripts
  drop constraint if exists link_transcripts_source_check;

alter table public.link_transcripts
  add constraint link_transcripts_source_check
  check (source in ('youtube', 'tiktok', 'instagram'));

alter table public.link_transcripts
  drop constraint if exists link_transcripts_provider_check;

alter table public.link_transcripts
  add constraint link_transcripts_provider_check
  check (provider in ('ytdlp', 'browser', 'disk_backfill', 'manual', 'whisper'));

comment on column public.link_transcripts.source is
  'Platform the transcript belongs to: youtube | tiktok | instagram (0059).';
comment on column public.link_transcripts.provider is
  'How the text was obtained: ytdlp/browser read the platform caption track, whisper transcribed the audio locally, disk_backfill/manual are operator imports (0059).';

commit;
